import React, { createContext, useContext, useState } from 'react';

const TRANSLATIONS = {
  en: {
    // Days (Sunday=0)
    day_sun: 'Sun', day_mon: 'Mon', day_tue: 'Tue', day_wed: 'Wed',
    day_thu: 'Thu', day_fri: 'Fri', day_sat: 'Sat',
    // Day short array helper
    days_short: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    // Months full
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    // Months short
    months_short: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    // Page titles & subtitles
    page_dashboard:         'Dashboard',
    page_dashboard_sub:     'Overview of your learning center',
    page_students:          'Students',
    page_students_sub:      'Manage enrolled students',
    page_groups:            'Groups',
    page_groups_sub:        'Manage classes and groups',
    page_teachers:          'Staff',
    page_teachers_sub:      'Manage teachers and admins',
    page_payments:          'Payments',
    page_payments_sub:      'Track income and debtors',
    page_attendance:        'Attendance',
    page_attendance_sub:    'Mark and review attendance',
    page_schedule:          'Schedule',
    page_schedule_sub:      'Weekly timetable board',
    page_analytics:         'Analytics',
    page_analytics_sub:     'Reports and performance insights',
    page_salary:            'My Salary',
    page_salary_sub:        'Your earnings and teaching stats',
    page_salary_admin:      'Salary Management',
    page_salary_admin_sub:  'Review and approve teacher salaries',
    page_settings:          'Settings',
    page_settings_sub:      'Manage your preferences and account',
    page_archive:           'Archive',
    page_archive_sub:       'Archived students — all data preserved',
    page_leads:             'Leads',
    page_leads_sub:         'Track and convert prospective students',
    page_earnings:          'My Earnings',
    page_earnings_sub:      'Income breakdown from your lessons',
    page_admin_earnings:    'Earnings Overview',
    page_admin_earnings_sub:'Teacher earnings and financial summary',
    page_lessons:           'Lessons',
    page_lessons_sub:       'Lesson history and attendance records',
    page_finances:          'Financial Analysis',
    page_finances_sub:      'Income vs expenses — profit breakdown',
    // Sidebar nav
    nav_dashboard:  'Dashboard',
    nav_overview:   'Overview',
    nav_students:   'Students',
    nav_groups:     'Groups',
    nav_teachers:   'Teachers',
    nav_attendance: 'Attendance',
    nav_schedule:   'Schedule',
    nav_lessons:    'Lessons',
    nav_payments:   'Payments',
    nav_analytics:  'Analytics',
    nav_earnings:   'Earnings',
    nav_my_earnings:'My Earnings',
    nav_salary:     'Salary',
    nav_salary_admin:'Salary',
    nav_leads:      'Leads',
    nav_archive:    'Archive',
    nav_settings:   'Settings',
    nav_sign_out:   'Sign out',
    nav_finances:   'Finances',
    // Attendance
    att_groups: 'Groups',
    att_loading: 'Loading\u2026',
    att_saving: 'Saving\u2026',
    att_saved: 'Saved',
    att_auto_saved: 'Auto-saved',
    att_print: 'Print',
    att_student_name: 'Student Name',
    att_no_group: 'Select a group from the left panel',
    att_no_students: 'No students in this group',
    att_no_lesson_days: 'no lesson days',
    att_teacher: 'Teacher',
    att_student_count: 'students',
    att_mark_all: 'Mark all present',
    att_hint_tap: 'Tap → toggle',
    att_hint_drag: 'Drag → multiple',
    att_hint_present: 'Present',
    att_hint_absent: 'Absent',
    // Settings
    set_profile: 'Profile',
    set_password: 'Change Password',
    set_system: 'System Settings',
    set_notifications: 'Notifications',
    set_appearance: 'Appearance',
    set_language: 'Language',
    set_dark_mode: 'Dark Mode',
    set_dark_mode_desc: 'Switch between light and dark theme',
    set_lang_desc: 'Choose your preferred language',
    set_save: 'Save changes',
    set_saving: 'Saving\u2026',
    set_full_name: 'Full name',
    set_email: 'Email',
    set_phone: 'Phone',
    set_role: 'Role',
    set_cur_password: 'Current password',
    set_new_password: 'New password',
    set_confirm_password: 'Confirm password',
    set_rate_per_lesson: 'Rate per lesson (UZS)',
    set_rate_hint: 'Used to calculate teacher salary',
    set_center_name: 'Learning center name',
    set_update_password: 'Update password',
    set_save_system: 'Save system settings',
    set_save_prefs: 'Save preferences',
    set_notif_payment: 'Payment due alerts',
    set_notif_payment_desc: 'Get notified when student payments are overdue',
    set_notif_student: 'New student registration',
    set_notif_student_desc: 'Alert when a new student is enrolled',
    set_notif_attendance: 'Daily attendance summary',
    set_notif_attendance_desc: 'Receive attendance report at end of day',
    set_notif_weekly: 'Weekly performance report',
    set_notif_weekly_desc: 'Summary of center performance every Monday',
  },
  uz: {
    // Days
    day_sun: 'Yak', day_mon: 'Du', day_tue: 'Se', day_wed: 'Ch',
    day_thu: 'Pa', day_fri: 'Ju', day_sat: 'Sh',
    days_short: ['Yak', 'Du', 'Se', 'Ch', 'Pa', 'Ju', 'Sh'],
    months: ['Yanvar', 'Fevral', 'Mart', 'Aprel', 'May', 'Iyun', 'Iyul', 'Avgust', 'Sentabr', 'Oktabr', 'Noyabr', 'Dekabr'],
    months_short: ['Yan', 'Fev', 'Mar', 'Apr', 'May', 'Iyn', 'Iyl', 'Avg', 'Sen', 'Okt', 'Noy', 'Dek'],
    // Page titles & subtitles
    page_dashboard:         'Boshqaruv',
    page_dashboard_sub:     "O'quv markaziga umumiy ko'rinish",
    page_students:          "O'quvchilar",
    page_students_sub:      "Ro'yxatdagi o'quvchilarni boshqarish",
    page_groups:            'Guruhlar',
    page_groups_sub:        'Sinflar va guruhlarni boshqarish',
    page_teachers:          'Xodimlar',
    page_teachers_sub:      "O'qituvchilar va adminlarni boshqarish",
    page_payments:          "To'lovlar",
    page_payments_sub:      'Daromad va qarzdorlarni kuzatish',
    page_attendance:        'Davomat',
    page_attendance_sub:    'Davomatni belgilash va ko\'rib chiqish',
    page_schedule:          'Jadval',
    page_schedule_sub:      'Haftalik dars jadvali',
    page_analytics:         'Tahlil',
    page_analytics_sub:     'Hisobotlar va samaradorlik ko\'rsatkichlari',
    page_salary:            'Mening maoshim',
    page_salary_sub:        'Daromad va dars statistikasi',
    page_salary_admin:      'Maosh boshqaruvi',
    page_salary_admin_sub:  "O'qituvchi maoshlarini ko'rib chiqish",
    page_settings:          'Sozlamalar',
    page_settings_sub:      'Sozlamalar va hisobni boshqarish',
    page_archive:           'Arxiv',
    page_archive_sub:       'Arxivlangan o\'quvchilar — barcha ma\'lumotlar saqlanadi',
    page_leads:             'Lidlar',
    page_leads_sub:         "Potensial o'quvchilarni kuzatish",
    page_earnings:          'Mening daromadim',
    page_earnings_sub:      'Darslardan daromad tahlili',
    page_admin_earnings:    'Daromad xulosasi',
    page_admin_earnings_sub:"O'qituvchi daromadlari va moliyaviy xulosa",
    page_lessons:           'Darslar',
    page_lessons_sub:       'Dars tarixi va davomat yozuvlari',
    page_finances:          'Moliyaviy tahlil',
    page_finances_sub:      'Daromad va xarajatlar — foyda tahlili',
    // Sidebar nav
    nav_dashboard:  'Boshqaruv',
    nav_students:   "O'quvchilar",
    nav_groups:     'Guruhlar',
    nav_teachers:   "O'qituvchilar",
    nav_attendance: 'Davomat',
    nav_schedule:   'Jadval',
    nav_lessons:    'Darslar',
    nav_payments:   "To'lovlar",
    nav_analytics:  'Tahlil',
    nav_earnings:   'Daromad',
    nav_my_earnings:"Mening daromadim",
    nav_salary:     'Maosh',
    nav_salary_admin:'Maosh',
    nav_leads:      'Lidlar',
    nav_archive:    'Arxiv',
    nav_settings:   'Sozlamalar',
    nav_sign_out:   'Chiqish',
    nav_finances:   'Moliya',
    // Attendance
    att_groups: 'Guruhlar',
    att_loading: 'Yuklanmoqda\u2026',
    att_saving: 'Saqlanmoqda\u2026',
    att_saved: 'Saqlandi',
    att_auto_saved: 'Bulutda saqlangan',
    att_print: 'Chop etish',
    att_student_name: "O'quvchi ismi",
    att_no_group: 'Chap paneldan guruh tanlang',
    att_no_students: "Bu guruhda o'quvchilar yo'q",
    att_no_lesson_days: 'dars kunlari yo\'q',
    att_teacher: "O'qituvchi",
    att_student_count: "o'quvchi",
    att_mark_all: 'Barchasini keldi',
    att_hint_tap: 'Bosing → belgilash',
    att_hint_drag: "Sudrab o'ting → bir nechta",
    att_hint_present: 'Keldi',
    att_hint_absent: "Sababsiz/Yo'q",
    set_profile: 'Profil',
    set_password: "Parolni o'zgartirish",
    set_system: 'Tizim sozlamalari',
    set_notifications: 'Bildirishnomalar',
    set_appearance: "Ko'rinish",
    set_language: 'Til',
    set_dark_mode: 'Tungi rejim',
    set_dark_mode_desc: "Yorqin va qorong'u mavzular o'rtasida almashtiring",
    set_lang_desc: "O'zingizga qulay tilni tanlang",
    set_save: 'Saqlash',
    set_saving: 'Saqlanmoqda\u2026',
    set_full_name: "To'liq ism",
    set_email: 'Elektron pochta',
    set_phone: 'Telefon',
    set_role: 'Rol',
    set_cur_password: 'Joriy parol',
    set_new_password: 'Yangi parol',
    set_confirm_password: 'Parolni tasdiqlash',
    set_rate_per_lesson: "Dars uchun tarif (so'm)",
    set_rate_hint: "O'qituvchi maoshini hisoblash uchun ishlatiladi",
    set_center_name: "O'quv markazi nomi",
    set_update_password: 'Parolni yangilash',
    set_save_system: 'Tizim sozlamalarini saqlash',
    set_save_prefs: 'Afzalliklarni saqlash',
    set_notif_payment: "To'lov eslatmalari",
    set_notif_payment_desc: "O'quvchi to'lovlari muddati o'tganda xabar bering",
    set_notif_student: "Yangi o'quvchi ro'yxatga olish",
    set_notif_student_desc: "Yangi o'quvchi qo'shilganda xabar bering",
    set_notif_attendance: 'Kunlik davomat xulosasi',
    set_notif_attendance_desc: 'Kun oxirida davomat hisobotini oling',
    set_notif_weekly: "Haftalik ko'rsatkich hisoboti",
    set_notif_weekly_desc: "Har dushanba kuni markaz ko'rsatkichlari xulosasi",
  },
  ru: {
    // Days
    day_sun: 'Вс', day_mon: 'Пн', day_tue: 'Вт', day_wed: 'Ср',
    day_thu: 'Чт', day_fri: 'Пт', day_sat: 'Сб',
    days_short: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
    months: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
    months_short: ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
    // Page titles & subtitles
    page_dashboard:         'Панель управления',
    page_dashboard_sub:     'Общий обзор учебного центра',
    page_students:          'Ученики',
    page_students_sub:      'Управление зачисленными учениками',
    page_groups:            'Группы',
    page_groups_sub:        'Управление классами и группами',
    page_teachers:          'Сотрудники',
    page_teachers_sub:      'Управление учителями и администраторами',
    page_payments:          'Платежи',
    page_payments_sub:      'Отслеживание доходов и должников',
    page_attendance:        'Посещаемость',
    page_attendance_sub:    'Отметка и просмотр посещаемости',
    page_schedule:          'Расписание',
    page_schedule_sub:      'Еженедельное расписание занятий',
    page_analytics:         'Аналитика',
    page_analytics_sub:     'Отчёты и показатели эффективности',
    page_salary:            'Моя зарплата',
    page_salary_sub:        'Доходы и статистика преподавания',
    page_salary_admin:      'Управление зарплатой',
    page_salary_admin_sub:  'Просмотр и утверждение зарплат учителей',
    page_settings:          'Настройки',
    page_settings_sub:      'Управление настройками и аккаунтом',
    page_archive:           'Архив',
    page_archive_sub:       'Архивированные ученики — все данные сохранены',
    page_leads:             'Лиды',
    page_leads_sub:         'Отслеживание потенциальных учеников',
    page_earnings:          'Мои доходы',
    page_earnings_sub:      'Разбивка дохода по урокам',
    page_admin_earnings:    'Обзор доходов',
    page_admin_earnings_sub:'Доходы учителей и финансовая сводка',
    page_lessons:           'Уроки',
    page_lessons_sub:       'История уроков и записи посещаемости',
    page_finances:          'Финансовый анализ',
    page_finances_sub:      'Доходы и расходы — разбивка прибыли',
    // Sidebar nav
    nav_dashboard:   'Панель',
    nav_students:    'Ученики',
    nav_groups:      'Группы',
    nav_teachers:    'Учителя',
    nav_attendance:  'Посещаемость',
    nav_schedule:    'Расписание',
    nav_lessons:     'Уроки',
    nav_payments:    'Платежи',
    nav_analytics:   'Аналитика',
    nav_earnings:    'Доходы',
    nav_my_earnings: 'Мои доходы',
    nav_salary:      'Зарплата',
    nav_salary_admin:'Зарплата',
    nav_leads:       'Лиды',
    nav_archive:     'Архив',
    nav_settings:    'Настройки',
    nav_sign_out:    'Выйти',
    nav_finances:    'Финансы',
    // Attendance
    att_groups:          'Группы',
    att_loading:         'Загрузка\u2026',
    att_saving:          'Сохранение\u2026',
    att_saved:           'Сохранено',
    att_auto_saved:      'Автосохранено',
    att_print:           'Печать',
    att_student_name:    'Имя ученика',
    att_no_group:        'Выберите группу на левой панели',
    att_no_students:     'В этой группе нет учеников',
    att_no_lesson_days:  'нет учебных дней',
    att_teacher:         'Учитель',
    att_student_count:   'учеников',
    att_mark_all:        'Отметить всех присутствующими',
    att_hint_tap:        'Нажмите → переключить',
    att_hint_drag:       'Перетащите → несколько',
    att_hint_present:    'Присутствует',
    att_hint_absent:     'Отсутствует',
    // Settings
    set_profile:              'Профиль',
    set_password:             'Изменить пароль',
    set_system:               'Системные настройки',
    set_notifications:        'Уведомления',
    set_appearance:           'Внешний вид',
    set_language:             'Язык',
    set_dark_mode:            'Тёмный режим',
    set_dark_mode_desc:       'Переключение между светлой и тёмной темой',
    set_lang_desc:            'Выберите предпочитаемый язык',
    set_save:                 'Сохранить',
    set_saving:               'Сохранение\u2026',
    set_full_name:            'Полное имя',
    set_email:                'Эл. почта',
    set_phone:                'Телефон',
    set_role:                 'Роль',
    set_cur_password:         'Текущий пароль',
    set_new_password:         'Новый пароль',
    set_confirm_password:     'Подтвердить пароль',
    set_rate_per_lesson:      'Тариф за урок (сум)',
    set_rate_hint:            'Используется для расчёта зарплаты учителя',
    set_center_name:          'Название учебного центра',
    set_update_password:      'Обновить пароль',
    set_save_system:          'Сохранить системные настройки',
    set_save_prefs:           'Сохранить настройки',
    set_notif_payment:        'Уведомления об оплате',
    set_notif_payment_desc:   'Уведомлять, когда платежи ученика просрочены',
    set_notif_student:        'Регистрация нового ученика',
    set_notif_student_desc:   'Уведомлять при зачислении нового ученика',
    set_notif_attendance:     'Ежедневная сводка посещаемости',
    set_notif_attendance_desc:'Получать отчёт о посещаемости в конце дня',
    set_notif_weekly:         'Еженедельный отчёт',
    set_notif_weekly_desc:    'Сводка по центру каждый понедельник',
  },
};

const LangContext = createContext(null);

export const LangProvider = ({ children }) => {
  const [lang, setLangState] = useState(() => localStorage.getItem('lang') || 'en');

  const setLang = (newLang) => {
    localStorage.setItem('lang', newLang);
    setLangState(newLang);
  };

  const t = (key) => {
    const dict = TRANSLATIONS[lang] || TRANSLATIONS.en;
    return key in dict ? dict[key] : (TRANSLATIONS.en[key] ?? key);
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used within LangProvider');
  return ctx;
};
